import { StatusCodes } from "http-status-codes";
import Project from "../models/projectModel.js";
import Task from "../models/taskModel.js";
import Comment from "../models/commentModel.js";
import Attachment from "../models/attachmentModel.js";
import AppError from "../utils/AppError.js";

/**
 * Create a new project in the workspace
 */
export const createProject = async (req, res, next) => {
  try {
    const { name, description, status, startDate, dueDate } = req.body;
    // userId and workspace are already loaded by checkWorkspaceMembership middleware
    const userId = req.userId;
    const workspace = req.workspace;

    // Create new project (key will be auto-generated by pre-save hook)
    const project = new Project({
      workspace: workspace._id,
      name,
      description,
      owner: userId,
      status: status || "active",
      startDate: startDate || null,
      dueDate: dueDate || null,
    });

    await project.save();

    // Populate owner details
    await project.populate("owner", "firstName lastName email profileImage");

    res.status(StatusCodes.CREATED).json({
      success: true,
      message: "Project created successfully",
      project: {
        id: project._id,
        workspace: project.workspace,
        name: project.name,
        key: project.key,
        description: project.description,
        owner: {
          id: project.owner._id,
          firstName: project.owner.firstName,
          lastName: project.owner.lastName,
          email: project.owner.email,
          profileImage: project.owner.profileImage,
        },
        status: project.status,
        startDate: project.startDate,
        dueDate: project.dueDate,
        createdAt: project.createdAt,
        updatedAt: project.updatedAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get all projects in a workspace
 */
export const getWorkspaceProjects = async (req, res, next) => {
  try {
    const workspace = req.workspace;

    // Optional query filters
    const { status } = req.query;

    const filter = {
      workspace: workspace._id,
      deletedAt: null,
    };

    if (status) {
      filter.status = status;
    }

    const projects = await Project.find(filter)
      .populate("owner", "firstName lastName email profileImage")
      .sort({ createdAt: -1 });

    const projectsWithTaskCount = await Promise.all(
      projects.map(async (project) => {
        const taskCount = await Task.countDocuments({
          project: project._id,
          deletedAt: null,
        });

        return {
          id: project._id,
          workspace: project.workspace,
          name: project.name,
          key: project.key,
          description: project.description,
          owner: {
            id: project.owner._id,
            firstName: project.owner.firstName,
            lastName: project.owner.lastName,
            email: project.owner.email,
            profileImage: project.owner.profileImage,
          },
          status: project.status,
          startDate: project.startDate,
          dueDate: project.dueDate,
          taskCount,
          createdAt: project.createdAt,
          updatedAt: project.updatedAt,
        };
      }),
    );

    res.status(StatusCodes.OK).json({
      success: true,
      count: projectsWithTaskCount.length,
      projects: projectsWithTaskCount,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get a single project by ID
 */
export const getProjectById = async (req, res, next) => {
  try {
    const { projectId } = req.params;
    const workspace = req.workspace;

    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    }).populate("owner", "firstName lastName email profileImage");

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    // Get task count
    const taskCount = await Task.countDocuments({
      project: project._id,
      deletedAt: null,
    });

    res.status(StatusCodes.OK).json({
      success: true,
      project: {
        id: project._id,
        workspace: project.workspace,
        name: project.name,
        key: project.key,
        description: project.description,
        owner: {
          id: project.owner._id,
          firstName: project.owner.firstName,
          lastName: project.owner.lastName,
          email: project.owner.email,
          profileImage: project.owner.profileImage,
        },
        status: project.status,
        startDate: project.startDate,
        dueDate: project.dueDate,
        taskCount,
        createdAt: project.createdAt,
        updatedAt: project.updatedAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Update a project
 */
export const updateProject = async (req, res, next) => {
  try {
    const { name, description, status, startDate, dueDate } = req.body;
    const { projectId } = req.params;
    const workspace = req.workspace;

    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    });

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    // Update fields if provided
    if (name !== undefined) project.name = name;
    if (description !== undefined) project.description = description;
    if (status !== undefined) project.status = status;
    if (startDate !== undefined) project.startDate = startDate || null;
    if (dueDate !== undefined) project.dueDate = dueDate || null;

    await project.save();

    // Populate owner details
    await project.populate("owner", "firstName lastName email profileImage");

    res.status(StatusCodes.OK).json({
      success: true,
      message: "Project updated successfully",
      project: {
        id: project._id,
        workspace: project.workspace,
        name: project.name,
        key: project.key,
        description: project.description,
        owner: {
          id: project.owner._id,
          firstName: project.owner.firstName,
          lastName: project.owner.lastName,
          email: project.owner.email,
          profileImage: project.owner.profileImage,
        },
        status: project.status,
        startDate: project.startDate,
        dueDate: project.dueDate,
        createdAt: project.createdAt,
        updatedAt: project.updatedAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Delete a project (soft delete with cascading)
 */
export const deleteProject = async (req, res, next) => {
  try {
    const { projectId } = req.params;
    const workspace = req.workspace;

    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    });

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    const deletedAt = new Date();

    // Soft delete the project
    project.deletedAt = deletedAt;
    await project.save();

    // Cascade soft delete to all related entities
    const tasks = await Task.find({
      project: project._id,
      deletedAt: null,
    }).select("_id");

    const taskIds = tasks.map((t) => t._id);

    await Promise.all([
      Task.updateMany({ project: project._id, deletedAt: null }, { deletedAt }),
      // Soft delete all comments on tasks in this project
      taskIds.length > 0
        ? Comment.updateMany(
            { task: { $in: taskIds }, deletedAt: null },
            { deletedAt },
          )
        : Promise.resolve(),
      // Soft delete all attachments related to this project
      Attachment.updateMany(
        { project: project._id, deletedAt: null },
        { deletedAt },
      ),
    ]);

    res.status(StatusCodes.OK).json({
      success: true,
      message: "Project and all related data deleted successfully",
    });
  } catch (error) {
    next(error);
  }
};
