import { StatusCodes } from "http-status-codes";
import Task from "../models/taskModel.js";
import Project from "../models/projectModel.js";
import Comment from "../models/commentModel.js";
import Attachment from "../models/attachmentModel.js";
import AppError from "../utils/AppError.js";

/**
 * Create a new task in the project
 */
export const createTask = async (req, res, next) => {
  try {
    const {
      title,
      description,
      status,
      priority,
      assignees,
      dueDate,
      estimatedHours,
    } = req.body;
    const { projectId } = req.params;
    const userId = req.userId;
    const workspace = req.workspace;

    // Verify project exists and belongs to the workspace
    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    });

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    // Create new task (ticketNumber will be auto-generated by pre-save hook)
    const task = new Task({
      project: project._id,
      title,
      description,
      status: status || undefined,
      priority: priority || undefined,
      reporter: userId,
      assignees: assignees || [],
      dueDate: dueDate || null,
      estimatedHours: estimatedHours || null,
    });

    await task.save();

    // Populate references for response
    await task.populate([
      { path: "reporter", select: "firstName lastName email profileImage" },
      { path: "assignees", select: "firstName lastName email profileImage" },
      { path: "project", select: "key name" },
    ]);

    res.status(StatusCodes.CREATED).json({
      success: true,
      message: "Task created successfully",
      task: {
        id: task._id,
        ticketId: `${task.project.key}-${task.ticketNumber}`,
        ticketNumber: task.ticketNumber,
        project: {
          id: task.project._id,
          key: task.project.key,
          name: task.project.name,
        },
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
        reporter: {
          id: task.reporter._id,
          firstName: task.reporter.firstName,
          lastName: task.reporter.lastName,
          email: task.reporter.email,
          profileImage: task.reporter.profileImage,
        },
        assignees: task.assignees.map((assignee) => ({
          id: assignee._id,
          firstName: assignee.firstName,
          lastName: assignee.lastName,
          email: assignee.email,
          profileImage: assignee.profileImage,
        })),
        dueDate: task.dueDate,
        estimatedHours: task.estimatedHours,
        order: task.order,
        createdAt: task.createdAt,
        updatedAt: task.updatedAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get all tasks in a project
 */
export const getProjectTasks = async (req, res, next) => {
  try {
    const { projectId } = req.params;
    const workspace = req.workspace;

    // Optional query filters
    const { status, priority, assignee, search } = req.query;

    // Verify project exists and belongs to the workspace
    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    });

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    const filter = {
      project: project._id,
      deletedAt: null,
    };

    // Apply filters
    if (status) {
      filter.status = status;
    }

    if (priority) {
      filter.priority = priority;
    }

    if (assignee) {
      filter.assignees = assignee;
    }

    // Text search on title and description
    if (search) {
      filter.$text = { $search: search };
    }

    const tasks = await Task.find(filter)
      .populate("reporter", "firstName lastName email profileImage")
      .populate("assignees", "firstName lastName email profileImage")
      .populate("project", "key name")
      .sort({ order: 1, createdAt: -1 });

    const tasksWithDetails = tasks.map((task) => ({
      id: task._id,
      ticketId: `${task.project.key}-${task.ticketNumber}`,
      ticketNumber: task.ticketNumber,
      title: task.title,
      description: task.description,
      status: task.status,
      priority: task.priority,
      reporter: {
        id: task.reporter._id,
        firstName: task.reporter.firstName,
        lastName: task.reporter.lastName,
        email: task.reporter.email,
        profileImage: task.reporter.profileImage,
      },
      assignees: task.assignees.map((assignee) => ({
        id: assignee._id,
        firstName: assignee.firstName,
        lastName: assignee.lastName,
        email: assignee.email,
        profileImage: assignee.profileImage,
      })),
      dueDate: task.dueDate,
      estimatedHours: task.estimatedHours,
      order: task.order,
      createdAt: task.createdAt,
      updatedAt: task.updatedAt,
    }));

    res.status(StatusCodes.OK).json({
      success: true,
      count: tasksWithDetails.length,
      tasks: tasksWithDetails,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get a single task by ID
 */
export const getTaskById = async (req, res, next) => {
  try {
    const { projectId, taskId } = req.params;
    const workspace = req.workspace;

    // Verify project exists and belongs to the workspace
    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    });

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    const task = await Task.findOne({
      _id: taskId,
      project: project._id,
      deletedAt: null,
    })
      .populate("reporter", "firstName lastName email profileImage")
      .populate("assignees", "firstName lastName email profileImage")
      .populate("project", "key name");

    if (!task) {
      throw new AppError("Task not found", StatusCodes.NOT_FOUND);
    }

    // Get comment count
    const commentCount = await Comment.countDocuments({
      task: task._id,
      deletedAt: null,
    });

    // Get attachment count
    const attachmentCount = await Attachment.countDocuments({
      task: task._id,
      deletedAt: null,
    });

    res.status(StatusCodes.OK).json({
      success: true,
      task: {
        id: task._id,
        ticketId: `${task.project.key}-${task.ticketNumber}`,
        ticketNumber: task.ticketNumber,
        project: {
          id: task.project._id,
          key: task.project.key,
          name: task.project.name,
        },
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
        reporter: {
          id: task.reporter._id,
          firstName: task.reporter.firstName,
          lastName: task.reporter.lastName,
          email: task.reporter.email,
          profileImage: task.reporter.profileImage,
        },
        assignees: task.assignees.map((assignee) => ({
          id: assignee._id,
          firstName: assignee.firstName,
          lastName: assignee.lastName,
          email: assignee.email,
          profileImage: assignee.profileImage,
        })),
        dueDate: task.dueDate,
        estimatedHours: task.estimatedHours,
        order: task.order,
        commentCount,
        attachmentCount,
        createdAt: task.createdAt,
        updatedAt: task.updatedAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Update a task
 */
export const updateTask = async (req, res, next) => {
  try {
    const {
      title,
      description,
      status,
      priority,
      assignees,
      dueDate,
      estimatedHours,
      order,
    } = req.body;
    const { projectId, taskId } = req.params;
    const workspace = req.workspace;

    // Verify project exists and belongs to the workspace
    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    });

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    const task = await Task.findOne({
      _id: taskId,
      project: project._id,
      deletedAt: null,
    });

    if (!task) {
      throw new AppError("Task not found", StatusCodes.NOT_FOUND);
    }

    // Update fields if provided
    if (title !== undefined) task.title = title;
    if (description !== undefined) task.description = description;
    if (status !== undefined) task.status = status;
    if (priority !== undefined) task.priority = priority;
    if (assignees !== undefined) task.assignees = assignees;
    if (dueDate !== undefined) task.dueDate = dueDate || null;
    if (estimatedHours !== undefined) {
      task.estimatedHours = estimatedHours || null;
    }
    if (order !== undefined) task.order = order;

    await task.save();

    // Populate references for response
    await task.populate([
      { path: "reporter", select: "firstName lastName email profileImage" },
      { path: "assignees", select: "firstName lastName email profileImage" },
      { path: "project", select: "key name" },
    ]);

    res.status(StatusCodes.OK).json({
      success: true,
      message: "Task updated successfully",
      task: {
        id: task._id,
        ticketId: `${task.project.key}-${task.ticketNumber}`,
        ticketNumber: task.ticketNumber,
        project: {
          id: task.project._id,
          key: task.project.key,
          name: task.project.name,
        },
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
        reporter: {
          id: task.reporter._id,
          firstName: task.reporter.firstName,
          lastName: task.reporter.lastName,
          email: task.reporter.email,
          profileImage: task.reporter.profileImage,
        },
        assignees: task.assignees.map((assignee) => ({
          id: assignee._id,
          firstName: assignee.firstName,
          lastName: assignee.lastName,
          email: assignee.email,
          profileImage: assignee.profileImage,
        })),
        dueDate: task.dueDate,
        estimatedHours: task.estimatedHours,
        order: task.order,
        createdAt: task.createdAt,
        updatedAt: task.updatedAt,
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Delete a task (soft delete with cascading)
 */
export const deleteTask = async (req, res, next) => {
  try {
    const { projectId, taskId } = req.params;
    const workspace = req.workspace;

    // Verify project exists and belongs to the workspace
    const project = await Project.findOne({
      _id: projectId,
      workspace: workspace._id,
      deletedAt: null,
    });

    if (!project) {
      throw new AppError("Project not found", StatusCodes.NOT_FOUND);
    }

    const task = await Task.findOne({
      _id: taskId,
      project: project._id,
      deletedAt: null,
    });

    if (!task) {
      throw new AppError("Task not found", StatusCodes.NOT_FOUND);
    }

    const deletedAt = new Date();

    // Soft delete the task
    task.deletedAt = deletedAt;
    await task.save();

    // Cascade soft delete to all related entities
    await Promise.all([
      // Soft delete all comments on this task
      Comment.updateMany({ task: task._id, deletedAt: null }, { deletedAt }),
      // Soft delete all attachments on this task
      Attachment.updateMany({ task: task._id, deletedAt: null }, { deletedAt }),
    ]);

    res.status(StatusCodes.OK).json({
      success: true,
      message: "Task and all related data deleted successfully",
    });
  } catch (error) {
    next(error);
  }
};
